version: '3.7'

services:
  node:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    tty: true
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8081:8080"
    tty: true
